{"version":3,"file":"DatabaseException.js","sourceRoot":"","sources":["../../../src/api/exceptions/DatabaseException.ts"],"names":[],"mappings":";AAAA,yDAAyD;AACzD,mEAAmE;AACnE,iFAAiF;;AAEjF;;;;;;GAMG;AAEH,wDAAqD;AAGrD,uBAA+B,SAAQ,qBAAS;IAC5C,YAAY,IAAY,EAAE,KAAU;QAChC,MAAM,KAAK,GAAW,KAAK,CAAC,KAAK,CAAC,KAAK,CAAC,IAAI,CAAC,CAAC,CAAC,CAAC,CAAC;QACjD,KAAK,CAAC,GAAG,EAAE,IAAI,EAAE;YACb,KAAK,CAAC,SAAS,CAAC,CAAC,CAAC;SACrB,CAAC,CAAC;IACP,CAAC;CACJ;AAPD,8CAOC","sourcesContent":["// Copyright (c) 2017-2018, The Particl Market developers\n// Distributed under the GPL software license, see the accompanying\n// file COPYING or https://github.com/particl/particl-market/blob/develop/LICENSE\n\n/**\n * DatabaseException\n * ----------------------------------------\n *\n * This should be used for repository errors like\n * entity with this id already exists and stuff like that.\n */\n\nimport { Exception } from '../../core/api/Exception';\n\n\nexport class DatabaseException extends Exception {\n    constructor(text: string, error: any) {\n        const value: string = error.stack.split('\\n')[0];\n        super(400, text, [\n            value.substring(7)\n        ]);\n    }\n}\n"]}